# Generated by Django 5.1.5 on 2025-02-12 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=15)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('joindate', models.DateTimeField(auto_now_add=True, db_column='joinDate')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('activityid', models.AutoField(db_column='activityID', primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity',
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('logid', models.AutoField(db_column='logID', primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_audit_log',
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('profileid', models.AutoField(db_column='profileID', primary_key=True, serialize=False)),
                ('accountname', models.CharField(max_length=5, unique=True)),
                ('dateofbirth', models.DateField(db_column='dateOfBirth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('address', models.TextField()),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('settingid', models.AutoField(db_column='settingID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('do not disturb', 'Dnd')], max_length=14)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
