# Generated by Django 5.1.5 on 2025-02-12 07:52

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(db_column='phoneNumber', max_length=15, validators=[api.validators.validate_phoneNumber]),
        ),
    ]
