# Generated by Django 5.1.5 on 2025-02-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_date_joined_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='accountname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
