# Generated by Django 5.1.5 on 2025-02-20 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofiles_accountname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['userid'], 'verbose_name': 'user'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'user activity', 'verbose_name_plural': 'user activities'},
        ),
        migrations.AlterModelOptions(
            name='userauditlog',
            options={'verbose_name': 'user audit log', 'verbose_name_plural': 'user audit logs'},
        ),
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'user settings', 'verbose_name_plural': 'user settings'},
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='profileid',
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='userid',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
