# Generated by Django 5.1.5 on 2025-02-20 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_options_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='settingid',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='userid',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
