# Generated by Django 5.1.5 on 2025-02-23 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_usersettings_settingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.UUIDField(db_column='userID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
