# Generated by Django 5.1.5 on 2025-02-23 10:01

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(db_column='phoneNumber', max_length=15, unique=True, validators=[api.validators.validate_phoneNumber]),
        ),
    ]
