# Generated by Django 5.1.6 on 2025-03-09 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendTable',
            fields=[
                ('friendid', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Friend ID')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('REJ', 'Rejected'), ('ACC', 'Accepted')], default='PEN', max_length=3)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('fromUserid', models.ForeignKey(db_column='fromUserID', on_delete=django.db.models.deletion.CASCADE, related_name='fromUserid', to=settings.AUTH_USER_MODEL)),
                ('toUserid', models.ForeignKey(db_column='toUserID', on_delete=django.db.models.deletion.CASCADE, related_name='toUserId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
