# Generated by Django 5.1.6 on 2025-03-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_friendtable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('workoutid', models.AutoField(db_column='activityID', primary_key=True, serialize=False)),
                ('calories', models.PositiveIntegerField()),
                ('steps', models.PositiveIntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Record',
                'verbose_name_plural': 'Workout Records',
                'db_table': 'Workout_Record',
            },
        ),
        migrations.AddConstraint(
            model_name='workoutrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calories', 0), ('steps', 0)), _negated=True), name='non-zero calories or steps'),
        ),
    ]
