# Generated by Django 5.1.6 on 2025-03-11 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_friendtable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('workoutid', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Workout Record')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
