# Generated by Django 5.1.6 on 2025-03-12 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_friendtable_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendtable',
            name='fromUserid',
            field=models.ForeignKey(db_column='fromUserID', on_delete=django.db.models.deletion.CASCADE, related_name='friend_fromUserid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendtable',
            name='toUserid',
            field=models.ForeignKey(db_column='toUserID', on_delete=django.db.models.deletion.CASCADE, related_name='friend_toUserid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FriendActivity',
            fields=[
                ('activityid', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='activity id')),
                ('activity', models.CharField(choices=[('POK', 'Poke'), ('CHA', 'Challenge')], max_length=3)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('fromUserid', models.ForeignKey(db_column='fromUserID', on_delete=django.db.models.deletion.CASCADE, related_name='friendactivity_fromUserid', to=settings.AUTH_USER_MODEL)),
                ('toUserid', models.ForeignKey(db_column='toUserID', on_delete=django.db.models.deletion.CASCADE, related_name='friendactivity_toUserid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
