# Generated by Django 5.1.6 on 2025-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_workoutrecord_delete_useractivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendtable',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendtable',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workoutrecord',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutrecord',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutrecord',
            name='workoutid',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
