# Generated by Django 5.1.6 on 2025-03-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_workoutrecord_delete_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutrecord',
            options={'verbose_name': 'Workout Record', 'verbose_name_plural': 'Workout Records'},
        ),
        migrations.AddField(
            model_name='workoutrecord',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutrecord',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='workoutrecord',
            table='Workout_Record',
        ),
    ]
