# Generated by Django 5.1.6 on 2025-03-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_friendtable_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workoutrecord',
            table='workout_Record',
        ),
    ]
