# Generated by Django 5.1.6 on 2025-03-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_friendtable_fromuserid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendactivity',
            options={'verbose_name': 'Friend Activity', 'verbose_name_plural': 'Friend Activities'},
        ),
        migrations.AddConstraint(
            model_name='friendactivity',
            constraint=models.CheckConstraint(condition=models.Q(('toUserid', models.F('fromUserid')), _negated=True), name='no self poke'),
        ),
    ]
