# Generated by Django 5.1.6 on 2025-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_friendactivity_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendtable',
            constraint=models.UniqueConstraint(fields=('fromUserid', 'toUserid'), name='two-way friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendtable',
            constraint=models.UniqueConstraint(fields=('toUserid', 'fromUserid'), name='two-way friendship reverse'),
        ),
    ]
