# Generated by Django 5.1.6 on 2025-03-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_friendtable_two_way_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendactivity',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendactivity',
            name='acceptDate',
            field=models.DateTimeField(null=True),
        ),
    ]
