# Generated by Django 5.1.6 on 2025-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_friendactivity_accept_friendactivity_acceptdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendactivity',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='friendactivity',
            name='acceptDate',
        ),
        migrations.AddField(
            model_name='friendactivity',
            name='durationSecs',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='friendactivity',
            name='status',
            field=models.CharField(choices=[('ACC', 'Accept'), ('REJ', 'Reject'), ('CAN', 'Cancel'), ('EXP', 'Expired'), ('PEN', 'Pending')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='friendactivity',
            name='statusDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
