# Generated by Django 5.1.6 on 2025-03-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAchievement',
            fields=[
                ('id', models.AutoField(db_column='achievement_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameEnemy',
            fields=[
                ('id', models.AutoField(db_column='enemy_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('health', models.PositiveIntegerField(default=1)),
                ('damage', models.PositiveIntegerField(default=1)),
                ('speed', models.PositiveIntegerField(default=1)),
                ('defense', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('owner', models.OneToOneField(db_column='owner_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.AutoField(db_column='character_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('color_hex', models.CharField(max_length=7)),
                ('health', models.PositiveIntegerField(default=1)),
                ('speed', models.PositiveIntegerField(default=1)),
                ('strength', models.PositiveIntegerField(default=1)),
                ('stamina', models.PositiveIntegerField(default=1)),
                ('gamesave_id', models.ForeignKey(db_column='gamesave_id', on_delete=django.db.models.deletion.CASCADE, to='api.gamesave')),
            ],
        ),
        migrations.CreateModel(
            name='GameAchievementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('achievement_id', models.ForeignKey(db_column='achievement_id', on_delete=django.db.models.deletion.CASCADE, to='api.gameachievement')),
                ('gamesave_id', models.ForeignKey(db_column='gamesave_id', on_delete=django.db.models.deletion.CASCADE, to='api.gamesave')),
            ],
        ),
    ]
