# Generated by Django 5.1.6 on 2025-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_gameachievement_gameenemy_gamesave_gamecharacter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameenemy',
            options={'verbose_name_plural': 'Game enemies'},
        ),
        migrations.AddField(
            model_name='gamecharacter',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='color_hex',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
