# Generated by Django 5.1.6 on 2025-03-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_gameenemy_options_gamecharacter_selected_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamecharacter',
            constraint=models.UniqueConstraint(condition=models.Q(('selected', True)), fields=('gamesave_id',), name='unique-selected-per-gamesave'),
        ),
    ]
