# Generated by Django 5.1.6 on 2025-04-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_gamecharacter_color_hex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecharacter',
            name='class',
        ),
        migrations.AddField(
            model_name='gamecharacter',
            name='type',
            field=models.CharField(choices=[('KNIGHT', 'Knight'), ('ARCHER', 'Archer'), ('PAWN', 'Pawn')], db_column='type', default='PAWN', max_length=6),
        ),
    ]
