# Generated by Django 5.2 on 2025-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_gamecharacter_class_gamecharacter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecharacter',
            name='name',
            field=models.CharField(default='Unnamed', max_length=32),
        ),
    ]
