# Generated by Django 5.2 on 2025-04-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_gamecharacter_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutrecord',
            name='non-zero calories or steps',
        ),
    ]
