# Generated by Django 5.2 on 2025-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_workoutrecord_non_zero_calories_or_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendactivity',
            name='status',
            field=models.CharField(choices=[('REJ', 'Reject'), ('CAN', 'Cancel'), ('EXP', 'Expired'), ('PEN', 'Pending'), ('ONG', 'Ongoing'), ('FIN', 'Finished')], default='PEN', max_length=3),
        ),
    ]
