# Generated by Django 5.2 on 2025-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_friendactivity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='in_leaderboards',
            field=models.BooleanField(default=True, help_text='When True, user can participate in the leaderboards'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_edit',
            field=models.BooleanField(default=True, help_text='When True, user can edit their profile'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user_interact',
            field=models.BooleanField(default=True, help_text='When True, user can participate in the leaderboards'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='workout_share',
            field=models.BooleanField(default=True, help_text='When True, user can share their workout data'),
        ),
    ]
