# Generated by Django 5.2 on 2025-04-06 11:15

import api.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_usersettings_in_leaderboards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='status',
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='accountname',
            field=models.CharField(default=api.helper.generate_random_username, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='dateofbirth',
            field=models.DateField(db_column='dateOfBirth', null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='in_leaderboards',
            field=models.BooleanField(default=True, help_text='When True, user can participate in the leaderboards', verbose_name='Can Join Leaderboards'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_edit',
            field=models.BooleanField(default=True, help_text='When True, user can edit their profile', verbose_name='Can Edit Profile'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user_interact',
            field=models.BooleanField(default=True, help_text='When True, user can participate in the leaderboards', verbose_name='Can Interact with Users'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='workout_share',
            field=models.BooleanField(default=True, help_text='When True, user can share their workout data', verbose_name='Can Share Workout'),
        ),
    ]
