# Generated by Django 5.2 on 2025-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_userprofiles_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesave',
            name='attempts_lifetime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
