name: Back-end test

on:
  push:
    paths:
      - '!front-end/**'
      - 'back-end/**'
      - '!back-end/conf/**'
      - '!back-end/*.lock'
      - '!back-end/*.toml'
      - '!backend/*.gitignore'
  workflow_dispatch:

jobs:
   run-tests:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          sparse-checkout: |
            back-end
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install poetry
      uses: snok/install-poetry@v1.3.1
      with:
        virtualenvs-in-project: true
    - name: Install Dependencies
      run: |
        cd $GITHUB_WORKSPACE/back-end
        poetry install
    - name: Run Tests
      run: |
        cd $GITHUB_WORKSPACE/back-end
        poetry run python manage.py test --noinput --failfast
      env:
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        db_database: ${{ secrets.DB_DATABASE }}
        db_host: ${{ secrets.DB_HOST }}
        db_password: ${{ secrets.DB_PASSWORD }}
        db_user: ${{ secrets.DB_USER }}
        django_key: ${{ secrets.DJANGO_KEY }}

