name: Back-end test

on:
  push:
    paths:
      - '!front-end/**'
      - 'back-end/**.py'
      - '!back-end/conf/**'
      - '!back-end/*.lock'
      - '!back-end/*.toml'
      - '!backend/*.gitignore'
  workflow_dispatch:

jobs:
   run-tests:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    environment: TEST_SECRET
    steps:
    - uses: actions/checkout@v4
      with:
          sparse-checkout: |
            back-end
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install poetry
      uses: snok/install-poetry@v1.3.1
      with:
        virtualenvs-in-project: true
    - name: Install Dependencies
      run: |
        cd $GITHUB_WORKSPACE/back-end
        poetry install
    - name: Run Tests
      run: |
        cd $GITHUB_WORKSPACE/back-end
        poetry run python manage.py test --noinput --parallel
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DJANGO_KEY: ${{ secrets.DJANGO_KEY }}

